"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";
import ReactMarkdown from "react-markdown";
import rehypeSanitize from "rehype-sanitize";
import remarkGfm from "remark-gfm";
import remarkBreaks from "remark-breaks";
import { format } from "date-fns";
import { id as localeId, enUS as localeEn } from "date-fns/locale";

type TranslationKey = "sow" | "client" | "dateGenerated" | "signatureTitle" | "acceptedBy" | "timestamp" | "userAgent" | "sessionVerify" | "disclaimerText";

const TRANSLATIONS: Record<string, Record<TranslationKey, string>> = {
    en: {
        sow: "Statement of Work",
        client: "Client:",
        dateGenerated: "Date Generated:",
        signatureTitle: "Electronic Signature - Audit Trail",
        acceptedBy: "Accepted By",
        timestamp: "Timestamp (UTC)",
        userAgent: "User Agent",
        sessionVerify: "Session ID Verification",
        disclaimerText: "This document serves as a secure digital agreement generated by ProjectBill. The audit trail above validates non-repudiation of the contracting parties."
    },
    id: {
        sow: "Perjanjian Kerja (SOW)",
        client: "Klien:",
        dateGenerated: "Dibuat Tanggal:",
        signatureTitle: "Tanda Tangan Elektronik - Jejak Audit",
        acceptedBy: "Disetujui Oleh",
        timestamp: "Stempel Waktu (UTC)",
        userAgent: "User Agent",
        sessionVerify: "Verifikasi ID Sesi",
        disclaimerText: "Dokumen ini berfungsi sebagai perjanjian digital aman yang dihasilkan oleh ProjectBill. Jejak audit di atas memvalidasi nirsangkal (non-repudiation) dari pihak-pihak yang menyepakati kontrak."
    }
};

export default function SOWPrintPage() {
    const params = useParams();
    const router = useRouter();
    const invoiceId = params.id as string;

    const [project, setProject] = useState<{ title: string; client: { name: string }; terms: string; termsAcceptedAt: string; termsAcceptedUserAgent: string; termsAcceptedSessionId: string; language?: string; } | null>(null);
    const [language, setLanguage] = useState<"en" | "id">("en");
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        async function fetchProjectAndSettings() {
            try {
                const projRes = await fetch(`/api/invoices/${invoiceId}/public-sow`);

                if (!projRes.ok) throw new Error("Failed to fetch SOW");

                const projData = await projRes.json();
                setProject(projData);

                if (projData.language === "en") {
                    setLanguage("en");
                } else {
                    setLanguage("id");
                }
            } catch (error) {
                console.error(error);
                router.push(`/invoices/${invoiceId}`);
            } finally {
                setIsLoading(false);
            }
        }
        fetchProjectAndSettings();
    }, [invoiceId, router]);

    // Automatically trigger print dialog when loaded
    useEffect(() => {
        if (!isLoading && project) {
            // Small delay to ensure styles and fonts are applied
            setTimeout(() => {
                window.print();
            }, 500);
        }
    }, [isLoading, project]);

    if (isLoading) {
        return (
            <div className="flex h-screen items-center justify-center bg-white">
                <Loader2 className="w-8 h-8 animate-spin text-slate-400" />
            </div>
        );
    }

    if (!project) return null;

    const t = TRANSLATIONS[language];
    const dateLocale = language === "id" ? localeId : localeEn;
    const dateFormat = language === "id" ? "d MMM yyyy" : "MMM d, yyyy";

    return (
        <div className="bg-white text-slate-900 min-h-screen p-8 md:p-12 mx-auto max-w-[21cm]">
            <style jsx global>{`
                @media print {
                    @page {
                        size: A4;
                        margin: 2cm;
                    }
                    body {
                        background: white;
                    }
                    /* Ensure exact colors are printed */
                    * {
                        -webkit-print-color-adjust: exact !important;
                        print-color-adjust: exact !important;
                    }
                }
            `}</style>

            <div className="print-content block">
                <div className="flex justify-between items-start border-b border-slate-200 pb-8 mb-8">
                    <div>
                        <h1 className="text-3xl font-serif font-bold mb-2 text-slate-800 tracking-tight">{t.sow}</h1>
                        <h2 className="text-xl font-medium text-slate-600 tracking-tight">{project.title}</h2>
                    </div>
                    <div className="text-right text-sm text-slate-500 flex flex-col gap-1">
                        <p><strong className="text-slate-700">{t.client}</strong> {project.client.name}</p>
                        <p><strong className="text-slate-700">{t.dateGenerated}</strong> {format(new Date(), dateFormat, { locale: dateLocale })}</p>
                    </div>
                </div>

                <div className="prose prose-sm max-w-none text-slate-800 leading-relaxed text-justify mb-16">
                    <ReactMarkdown remarkPlugins={[remarkGfm, remarkBreaks]} rehypePlugins={[rehypeSanitize]}>
                        {project.terms}
                    </ReactMarkdown>
                </div>

                {project.termsAcceptedAt && (
                    <div className="mt-16 pt-6 border-t-2 border-slate-900">
                        <h3 className="font-bold text-lg mb-4 text-slate-900">{t.signatureTitle}</h3>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-y-4 gap-x-8 text-sm text-slate-700">
                            <div>
                                <span className="block font-semibold text-slate-900 mb-1">{t.acceptedBy}</span>
                                <span className="bg-slate-100 px-3 py-1.5 rounded inline-block w-full">{project.client.name}</span>
                            </div>
                            <div>
                                <span className="block font-semibold text-slate-900 mb-1">{t.timestamp}</span>
                                <span className="bg-slate-100 px-3 py-1.5 rounded inline-block w-full text-xs font-mono">{new Date(project.termsAcceptedAt).toUTCString()}</span>
                            </div>
                            <div>
                                <span className="block font-semibold text-slate-900 mb-1">{t.userAgent}</span>
                                <span className="bg-slate-100 px-3 py-1.5 rounded inline-block w-full text-[10px] break-all truncate" title={project.termsAcceptedUserAgent || "Unknown"}>{project.termsAcceptedUserAgent || "Unknown"}</span>
                            </div>
                            <div>
                                <span className="block font-semibold text-slate-900 mb-1">{t.sessionVerify}</span>
                                <span className="bg-slate-100 px-3 py-1.5 rounded inline-block w-full text-xs font-mono break-all">{project.termsAcceptedSessionId || "Unknown"}</span>
                            </div>
                        </div>

                        <p className="mt-8 text-[11px] text-slate-400 text-center italic">
                            {t.disclaimerText}
                        </p>
                    </div>
                )}
            </div>
        </div>
    );
}
