// AI Financial Co-Pilot — Type Definitions

export interface BaseMessage {
  id: string;
  role: "user" | "assistant" | "system" | "tool";
  content: string;
  metadata?: Record<string, unknown>;
  createdAt: Date;
}

export interface ChatMessage extends BaseMessage {}

export interface ChatRequest {
  conversationId?: string;
  message: string;
}

export interface ChatResponse {
  messageId: string;
  content: string;
  suggestions?: string[];
  structuredData?: StructuredField[];
}

export interface StructuredField {
  type: "cashflow" | "reminders" | "invoice_summary" | "client_insight" | "pricing_tip";
  data: Record<string, unknown>;
}

// Business context — flattened data for AI prompts
export interface BusinessContext {
  companyInfo: {
    name: string;
    email: string;
    logoUrl?: string;
  };
  stats: StatsSummary;
  recentInvoices: InvoiceSummary[];
  upcomingDeadlines: DeadlineSummary[];
  topClients: ClientSummary[];
}

export interface StatsSummary {
  totalClients: number;
  activeProjects: number;
  doneProjects: number;
  totalPaid: number;
  totalPending: number;
  unpaidInvoices: number;
  overdueInvoices: number;
}

export interface InvoiceSummary {
  id: string;
  number: string;
  amount: number;
  status: string;
  dueDate: Date | null;
  projectName: string;
  clientName: string;
}

export interface DeadlineSummary {
  title: string;
  deadline: Date;
  clientName: string;
  daysRemaining: number;
}

export interface ClientSummary {
  name: string;
  email: string;
  totalPaid: number;
  totalPending: number;
  projectCount: number;
  activeProjectCount: number;
}

// AgentConfig DTO (user-facing, no internal fields)
export interface AgentConfigDTO {
  provider: string;
  model: string;
  temperature: number;
  proactiveMode: boolean;
  locale: "id" | "en";
}

// AgentConfig input for PUT
export type AgentConfigInput = Partial<AgentConfigDTO>;

// Proactive insight — generated by the insights engine
export interface ProactiveInsight {
  type: "overdue_warning" | "cashflow_alert" | "client_suggestion" | "pricing_tip" | "follow_up_reminder";
  priority: "high" | "medium" | "low";
  message: string;
  messageEn?: string;
  action?: string; // API route or action to trigger
  actionLabel?: string; // Button text
  data?: Record<string, unknown>;
}

// Tool result envelope
export interface ToolResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

// SSE event types for streaming
export type SSEEvent =
  | { type: "chunk"; content: string }
  | { type: "tool_call"; tool: string; args: Record<string, unknown> }
  | { type: "tool_result"; tool: string; result: ToolResult }
  | { type: "done"; conversationId: string; messageId: string }
  | { type: "error"; message: string };

// Agent memory entry
export interface MemoryEntry {
  key: string;
  value: Record<string, unknown>;
  context?: string;
}
