"use server";

import { prisma } from "@/lib/prisma"
import { sendInvoiceEmail as baseSendInvoiceEmail } from "@/lib/email"

export async function sendInvoiceEmail(
  invoiceId: string,
  isAutoGenerated: boolean = false,
  customNotes?: string | null
) {
  try {
    const invoice = await prisma.invoice.findUnique({
      where: { id: invoiceId },
      include: {
        project: {
          include: {
            client: true
          }
        }
      }
    })

    if (!invoice || !invoice.project.client.email) {
      throw new Error("Invoice or Client Email not found")
    }

    const client = invoice.project.client
    const project = invoice.project

    const formatCurrency = new Intl.NumberFormat(
      project.currency === "IDR" ? "id-ID" : "en-US",
      {
        style: "currency",
        currency: project.currency || "IDR",
        minimumFractionDigits: 0,
      }
    )

    const amountStr = formatCurrency.format(Number(invoice.amount));
    const baseUrl = process.env.APP_URL || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "http://localhost:3000");
    const invoiceDetailUrl = `${baseUrl}/invoices/${invoice.id}`;

    // Fix potential issue where resend API keys fail silently
    try {
        const result = await baseSendInvoiceEmail({
          to: client.email!,
          clientName: client.name,
          projectTitle: project.title,
          invoiceId: invoice.invoiceNumber,
          dueDate: invoice.dueDate,
          amountStr: amountStr,
          invoiceLink: invoiceDetailUrl,
          lang: project.language as "id" | "en",
        });

        if (result.success && !result.mocked) {
          await prisma.invoice.update({
             where: { id: invoiceId },
             data: { emailStatus: 'sent' }
          });
        }

        if (!result.success && result.error) {
           throw result.error;
        }
        
        let mailtoData = undefined;
        if (result.mocked) {
           const subject = project.language === "en"
               ? `Invoice [${invoice.invoiceNumber}] for ${project.title} - Action Required`
               : `Invoice [${invoice.invoiceNumber}] untuk ${project.title} - Diperlukan Tindakan`;
           
           const body = project.language === "en"
               ? `Hello ${client.name},\n\nPlease find your invoice detail here:\n${invoiceDetailUrl}\n\nAmount due: ${amountStr}\n\nThank you!`
               : `Halo ${client.name},\n\nBerikut adalah detail tagihan Anda:\n${invoiceDetailUrl}\n\nTotal tagihan: ${amountStr}\n\nTerima kasih!`;
           
           mailtoData = { to: client.email!, subject, body };
        }
        
        return { 
          success: true, 
          manual: result.mocked, 
          message: result.mocked ? "Select your preferred email provider..." : undefined, 
          invoiceLink: result.mocked ? invoiceDetailUrl : undefined,
          mailtoData
        }
    } catch (emailError: any) {
        console.error("Failed to send email via Resend:", emailError);
        // Set status to failed
        await prisma.invoice.update({
          where: { id: invoiceId },
          data: { emailStatus: 'failed' }
        });
        return { success: false, error: emailError?.message || "Failed to send email" }
    }
  } catch (error) {
    console.error("Error generating/sending invoice email:", error)
    return { success: false, error: "Failed to send email" }
  }
}
